"use client";

// ASK-5 (물어보기 엔트리) — the empty state answers "오늘 뭘 물어볼까?" in one glance,
// with ZERO request-time LLM work (everything below is pre-generated by the 5-minute
// ask-feed refresher; this screen is a cache read):
//   ① 시장 한 줄 — live indices/FX strip, every figure tap-to-ask
//   ② 내 종목 질문거리 — per-ticker DEEP question cards (hook = the fresh fact that makes
//      the question timely) + capability chips per ticker
//   ③ Hot Trend — the macro/micro/market picture everyone shares, sourced
// Global rule: every tap FILLS the composer; the user always presses Enter themselves.
// A ticker whose pool isn't generated yet renders a "준비 중" skeleton — a gap, never
// fabricated content.

import { useEffect, useState } from "react";

type PulseItem = { label: string; ticker: string; price?: number | null; change_percent?: number | null; as_of?: string | null };
type WatchTick = { ticker: string; market: string; name?: string | null; price?: number | null; change_percent?: number | null };
type AskCard = { kind: string; question: string; hook: string; citations?: { source?: string; as_of?: string }[] };
type TickerPool = { market: string; ticker: string; name: string; cards: AskCard[]; generated_at?: string | null };

// ENT-4: capability chips per company — the product's real verbs, market-aware.
export function capabilityChips(name: string, market: string): { label: string; q: string }[] {
  const chips = [
    { label: "실적·재무", q: `${name} 최근 실적·재무 알려줘` },
    { label: "주가 차트", q: `${name} 최근 주가 흐름 차트로 보여줘` },
    { label: "밸류에이션", q: `${name} 밸류에이션 지표(PER·PBR·시가총액) 알려줘` },
    { label: "최근 공시", q: `${name} 최근 공시 뭐 있어?` },
    { label: "뉴스", q: `${name} 최근 뉴스 브리핑해줘` },
    { label: "과거 낙폭", q: `${name} 지금 낙폭이 과거와 비교하면 어때?` },
  ];
  chips.push(market === "KR"
    ? { label: "수급(외인·기관)", q: `${name} 외국인·기관 수급 어때?` }
    : { label: "거장 보유(13F)", q: `${name} 들고 있는 투자 거장 있어?` });
  return chips;
}

const fmtPct = (v?: number | null) =>
  v == null ? "" : `${v > 0 ? "▲" : v < 0 ? "▼" : ""}${Math.abs(v).toFixed(v >= 100 ? 0 : 1)}%`;

const TREND_TAG: Record<string, string> = { macro: "거시", micro: "미시", market: "시장" };

export default function CockpitEntry({ onPick, onQuestions }: {
  onPick: (q: string) => void;                       // fill the composer, focus — never send
  onQuestions?: (qs: string[]) => void;              // today's questions → rotating placeholder
}) {
  const [pulse, setPulse] = useState<PulseItem[]>([]);
  const [pulseAsOf, setPulseAsOf] = useState<string | null>(null);
  const [ticks, setTicks] = useState<WatchTick[]>([]);
  const [pools, setPools] = useState<TickerPool[]>([]);
  const [pending, setPending] = useState<{ ticker: string; name: string }[]>([]);
  const [hot, setHot] = useState<AskCard[]>([]);
  const [openTicker, setOpenTicker] = useState<string | null>(null);

  useEffect(() => {
    let dead = false;
    (async () => {
      try {
        const r = await fetch("/api/market/pulse");
        if (r.ok && !dead) {
          const d = await r.json();
          setPulse(d.items ?? []);
          setPulseAsOf(d.as_of ?? null);
        }
      } catch { /* the strip is optional — never blocks the composer */ }
      try {
        const r = await fetch("/api/market/watch");
        if (r.ok && !dead) setTicks(((await r.json()).tickers ?? []));
      } catch { /* optional */ }
      try {
        const r = await fetch("/api/ask-feed");
        if (r.ok && !dead) {
          const d = await r.json();
          const ps: TickerPool[] = d.tickers ?? [];
          setPools(ps);
          setPending(d.pending ?? []);
          setHot(d.hot_trend ?? []);
          const qs = ps.flatMap((p) => p.cards.map((c) => c.question)).slice(0, 6);
          if (qs.length) onQuestions?.(qs);
        }
      } catch { /* optional — the composer is always usable */ }
    })();
    return () => { dead = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const move = (t: string) => ticks.find((x) => x.ticker === t)?.change_percent;

  return (
    <div className="cockpit" data-testid="cockpit">
      {/* ① 시장 한 줄 */}
      {pulse.length > 0 && (
        <div className="ck-strip mono" title={pulseAsOf ? `as of ${pulseAsOf}` : undefined}>
          {pulse.map((p) => (
            <button key={p.ticker} type="button" className="ck-tickeritem"
              onClick={() => onPick(`오늘 ${p.label} 왜 ${((p.change_percent ?? 0) >= 0 ? "올랐" : "내렸")}는지 설명해줘`)}
              title="탭하면 질문이 입력창에 담깁니다">
              <span className="ck-lbl">{p.label}</span>
              <span className="ck-px">{p.price?.toLocaleString(undefined, { maximumFractionDigits: 1 })}</span>
              <span className={`ck-chg ${(p.change_percent ?? 0) >= 0 ? "up" : "down"}`}>{fmtPct(p.change_percent)}</span>
            </button>
          ))}
        </div>
      )}

      <h2 className="ck-h">오늘, 무엇을 물어볼까요?</h2>

      {/* ② 내 종목 질문거리 — 사전 생성된 딥 질문, 티커별 그룹 */}
      {(pools.length > 0 || pending.length > 0) && (
        <div className="ck-mine" data-testid="ck-mine">
          <div className="ck-sec-h mono">내 종목 질문거리</div>
          {pools.map((p) => (
            <div key={p.ticker} className="ck-pool">
              <button type="button" className={`ck-tick ${openTicker === p.ticker ? "on" : ""}`}
                onClick={() => setOpenTicker((v) => (v === p.ticker ? null : p.ticker))}>
                {p.name}
                {move(p.ticker) != null && (
                  <span className={`ck-chg ${(move(p.ticker) ?? 0) >= 0 ? "up" : "down"} mono`}> {fmtPct(move(p.ticker))}</span>
                )}
              </button>
              {p.cards.slice(0, openTicker === p.ticker ? 5 : 2).map((c, i) => (
                <button key={i} type="button" className="ck-sg" onClick={() => onPick(c.question)}>
                  <span className="ck-sg-hook">{c.hook}</span>
                  <span className="ck-sg-q">“{c.question}” →</span>
                  {c.citations?.[0]?.source ? <span className="ck-sg-src mono">{c.citations[0].source}</span> : null}
                </button>
              ))}
              {openTicker === p.ticker && (
                <div className="ck-caps" data-testid="ck-caps">
                  {capabilityChips(p.name, p.market).map((c) => (
                    <button key={c.label} type="button" className="ck-cap" onClick={() => onPick(c.q)}>{c.label}</button>
                  ))}
                </div>
              )}
            </div>
          ))}
          {pending.map((p) => (
            <div key={p.ticker} className="ck-pool ck-pending" data-testid="ck-pending">
              <span className="ck-tick">{p.name}</span>
              <span className="ck-sg-hook">질문거리 준비 중 — 다음 갱신에 채워집니다</span>
            </div>
          ))}
        </div>
      )}
      {pools.length === 0 && pending.length === 0 && (
        <div className="ck-mine ck-empty" data-testid="ck-nudge">
          <div className="ck-sec-h mono">내 종목 질문거리</div>
          <span className="ck-sg-hook">관심종목을 등록하면 이 자리에 매일 물어볼 거리를 준비해둡니다.</span>
        </div>
      )}

      {/* ③ Hot Trend — 거시/미시/시장, 전역 사전 생성 */}
      {hot.length > 0 && (
        <div className="ck-hot" data-testid="ck-hot">
          <div className="ck-sec-h mono">Hot Trend</div>
          {hot.map((c, i) => (
            <button key={i} type="button" className="ck-sg" onClick={() => onPick(c.question)}>
              <span className="ck-hot-tag mono">{TREND_TAG[c.kind] ?? c.kind}</span>
              <span className="ck-sg-hook">{c.hook}</span>
              <span className="ck-sg-q">“{c.question}” →</span>
              {c.citations?.[0]?.source ? <span className="ck-sg-src mono">{c.citations[0].source}</span> : null}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
