#!/usr/bin/env bash
# Split a monolithic .env into the topical env/*.env files.
#
# For each env/<name>.env.example, we take the variable NAMES it declares (including
# commented "# VAR=" optionals) and write env/<name>.env with those vars' values pulled
# from your existing .env. Anything in .env that no template claims is appended to
# env/app.env so nothing is lost. Existing env/*.env files are NOT overwritten (safety).
#
#   bash scripts/split_env.sh            # uses ./.env
#   bash scripts/split_env.sh path/.env  # a specific source
set -euo pipefail
cd "$(dirname "$0")/.."

SRC="${1:-.env}"
[ -f "$SRC" ] || { echo "no source env at '$SRC' — nothing to split (use option A in env/README.md)"; exit 0; }

# key -> value from the source (last assignment wins; keeps everything after the first '=')
declare -A VAL
while IFS= read -r line; do
  [[ "$line" =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]+)=(.*)$ ]] || continue
  VAL["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
done < "$SRC"

claimed_file="$(mktemp)"
trap 'rm -f "$claimed_file"' EXIT

for tmpl in env/*.env.example; do
  out="${tmpl%.example}"
  if [ -e "$out" ]; then echo "skip $out (already exists)"; continue; fi
  # var names this template declares (VAR= or # VAR=)
  names=$(grep -oE '^[[:space:]]*#?[[:space:]]*[A-Z][A-Z0-9_]+=' "$tmpl" | grep -oE '[A-Z][A-Z0-9_]+' | sort -u)
  {
    echo "# generated by scripts/split_env.sh from $SRC — edit freely"
    for n in $names; do
      echo "$n" >> "$claimed_file"
      if [ -n "${VAL[$n]+x}" ]; then echo "$n=${VAL[$n]}"; else echo "# $n="; fi
    done
  } > "$out"
  echo "wrote $out"
done

# anything in .env not claimed by any template → env/app.env (so nothing is lost)
if [ -e env/app.env ]; then
  extra=""
  for n in "${!VAL[@]}"; do grep -qxF "$n" "$claimed_file" || extra+="$n=${VAL[$n]}"$'\n'; done
  if [ -n "$extra" ]; then
    { echo ""; echo "# --- carried over from $SRC (unclaimed by any template) ---"; printf '%s' "$extra"; } >> env/app.env
    echo "appended $(printf '%s' "$extra" | grep -c '=') unclaimed var(s) to env/app.env"
  fi
fi
echo "done. Review env/*.env, then you can remove or empty $SRC."
