"""Studio ORM.

`User` maps a Google-authenticated email to its platform tenant/project/key
(held server-side, never sent to the browser). `Conversation`/`Message` store
chat history. `Agent` backs the agent builder.
`Watchlist`/`WatchlistItem` are the user's @groups (U1). `Integration` is the
messenger seam (F3).
"""

from __future__ import annotations

import secrets
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column

from studioapi.db import Base


def _uid(prefix: str) -> str:
    return f"{prefix}_{secrets.token_hex(8)}"


class User(Base):
    __tablename__ = "users"
    email: Mapped[str] = mapped_column(String(256), primary_key=True)
    tenant_id: Mapped[str] = mapped_column(String(48))
    project_id: Mapped[str] = mapped_column(String(48))
    api_key: Mapped[str] = mapped_column(String(80))  # the tenant platform key (server-side only)
    # Profile (seeded from the OAuth provider on first login; display name is user-editable).
    name: Mapped[str | None] = mapped_column(String(120), nullable=True)
    image: Mapped[str | None] = mapped_column(String(512), nullable=True)   # avatar URL (provider or set)
    # PLAN-1: guest | free | pro — quotas.py가 턴 한도, prepare_turn이 모델 티어,
    # apply_plan이 커넥터 엔타이틀먼트를 이 값에서 끌어낸다 (더 이상 display-only 아님).
    plan: Mapped[str] = mapped_column(String(24), default="free")
    plan_updated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    # REF-2: 피추천 가입 보너스 — bonus_turns_until까지 일일 한도에 +bonus_daily_turns.
    bonus_daily_turns: Mapped[int] = mapped_column(Integer, default=0)
    bonus_turns_until: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    # REF-1: 내 추천 코드(lazy 발급) + 나를 추천한 유저의 이메일.
    referral_code: Mapped[str | None] = mapped_column(String(16), unique=True, nullable=True)
    referred_by: Mapped[str | None] = mapped_column(String(256), nullable=True)
    # AUTH-4: 메일 발송 가능 여부 — 카카오 무이메일 센티널 계정은 False (메일러 게이트).
    email_verified: Mapped[bool] = mapped_column(Boolean, default=True)
    onboarded: Mapped[bool] = mapped_column(Boolean, default=False)  # completed the F1 onboarding
    # M-DESK: previous visit timestamp — bounds the desk feed's "since last visit" windows
    # (새로 들어온 공시 etc.). Updated each time the feed is served.
    last_seen_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class CardTap(Base):
    """RC-1: 질문 카드 탭 이벤트 — 어떤 kind에 유저가 반응하는지의 실측. 피드 합성이
    이 분포를 힌트로 받아 개인화한다(규칙 하드코딩 아님 — 프롬프트 컨텍스트)."""

    __tablename__ = "card_taps"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_email: Mapped[str] = mapped_column(String(256), index=True)
    kind: Mapped[str] = mapped_column(String(32))
    ticker: Mapped[str | None] = mapped_column(String(32), nullable=True)
    ts: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), index=True)


class DeskFeedCache(Base):
    """M-DESK (DK-3): the per-user desk-feed payload as generated by agent-engine. One row per
    user; refreshed when older than the TTL and deleted on any watchlist change (the feed is
    watchlist-derived, so an edit makes it wrong, not just stale)."""

    __tablename__ = "desk_feed_cache"
    user_email: Mapped[str] = mapped_column(ForeignKey("users.email"), primary_key=True)
    payload: Mapped[str] = mapped_column(Text)  # JSON {cards, generated_at, used_tools}
    generated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class AskFeedCache(Base):
    """ASK-6: cached ask-feed content. One row per SCOPE — ``news_feed`` (global, upserted by
    the 10-minute background refresher) or ``ticker:{MKT}:{TICKER}`` (upserted on demand when a
    user taps that ticker; shared by every user, TTL-gated). ``signature`` is the digest of the
    gathered records — when unchanged the generator keeps the cards and skips the LLM."""

    __tablename__ = "ask_feed_cache"
    scope: Mapped[str] = mapped_column(String(64), primary_key=True)
    payload: Mapped[str] = mapped_column(Text)  # JSON {cards, generated_at}
    signature: Mapped[str | None] = mapped_column(String(64), nullable=True)
    generated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())




class StandingQuestion(Base):
    """M-SA: a QUESTION the user subscribed to — not an alert rule. Created from the one-tap
    "🔔 이 질문 계속 지켜보기" chip after an answer whose evidence is periodic (cadence-gated).
    The desk-feed generation piggybacks a cheap SIGNATURE check (latest as_of / accession /
    bar date from the recorded source call); a changed signature yields a `standing_update`
    desk card. Delivery is the DESK, never a push channel (chat-first)."""

    __tablename__ = "standing_questions"
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("sq"))
    user_email: Mapped[str] = mapped_column(ForeignKey("users.email"), index=True)
    question: Mapped[str] = mapped_column(String(400))
    ticker: Mapped[str | None] = mapped_column(String(32), nullable=True)
    market: Mapped[str | None] = mapped_column(String(8), nullable=True)
    cadence: Mapped[str] = mapped_column(String(12), default="daily")   # daily | event | weekly
    # the signature source: ONE recorded tool call {tool, args} whose freshest identifier
    # (as_of / accession / bar date) stands in for "did the underlying data change?"
    probe: Mapped[str] = mapped_column(Text, default="{}")
    last_signature: Mapped[str | None] = mapped_column(String(256), nullable=True)
    last_checked_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    active: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class ShareLink(Base):
    """M-SHARE (SH-1): an immutable share snapshot — public read via unguessable token, revocable.
    payload = JSON snapshot (a share never silently changes; its as_of stays visible)."""

    __tablename__ = "share_links"
    token: Mapped[str] = mapped_column(String(48), primary_key=True)
    user_email: Mapped[str] = mapped_column(ForeignKey("users.email"), index=True)
    kind: Mapped[str] = mapped_column(String(12))            # artifact | verdict | note | quote
    title: Mapped[str] = mapped_column(String(160))
    payload: Mapped[str] = mapped_column(Text)
    image_path: Mapped[str | None] = mapped_column(String(256), nullable=True)  # OG PNG path (reserved)
    # SH-2b: the client-rendered OG card PNG, base64 (data URL body). Served by GET /shares/{token}/image
    # and referenced by the public page's og:image. Stored with the share so it needs no volume.
    og_image: Mapped[str | None] = mapped_column(Text, nullable=True)
    revoked: Mapped[bool] = mapped_column(Boolean, default=False)
    # V-4: 공개 페이지 뷰 카운터 (sendBeacon 실측 — 허수 없음)
    views: Mapped[int] = mapped_column(Integer, default=0)
    # IMP-13: shares expire (+90d default) — corrected/deleted research must not stay public forever
    expires_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class UserIdentity(Base):
    """AUTH-4: 소셜 계정 ↔ 유저 매핑 — (provider, provider_account_id)가 캐노니컬 이메일을
    가리킨다. 프로바이더가 이메일을 바꾸거나 안 줘도(카카오 비즈앱 전) 계정이 갈라지지 않고,
    이메일 연결 승격 시 이 행만 다시 가리키면 다음 로그인부터 새 이메일로 착지한다."""

    __tablename__ = "user_identities"
    __table_args__ = (UniqueConstraint("provider", "provider_account_id", name="uq_identity"),)
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    provider: Mapped[str] = mapped_column(String(24))
    provider_account_id: Mapped[str] = mapped_column(String(128))
    user_email: Mapped[str] = mapped_column(String(256), index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class EmailOtp(Base):
    """AUTH-2: 이메일 로그인 6자리 코드 — sha256만 저장, 10분 만료, 시도 5회, 1회 소비.
    발송 스로틀(이메일/IP 시간당)은 created_at·ip_hash 카운트로 판정한다."""

    __tablename__ = "email_otp"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    email: Mapped[str] = mapped_column(String(256), index=True)
    code_hash: Mapped[str] = mapped_column(String(64))
    expires_at: Mapped[datetime] = mapped_column(DateTime)
    attempts: Mapped[int] = mapped_column(Integer, default=0)
    consumed: Mapped[bool] = mapped_column(Boolean, default=False)
    ip_hash: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), index=True)


class ServiceState(Base):
    """GUEST-1: 서비스 수준 KV — 예: 공유 게스트 테넌트의 project/key(JSON). 서버 사이드 전용;
    브라우저에는 절대 내려가지 않는다."""

    __tablename__ = "service_state"
    key: Mapped[str] = mapped_column(String(64), primary_key=True)
    value: Mapped[str] = mapped_column(Text)  # JSON
    updated_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now(), onupdate=func.now())


class GuestSession(Base):
    """GUEST-1: 익명 체험 세션(디바이스 단위) — httpOnly 쿠키의 id가 PK. 평생 턴 캡의 주체이자
    IP 어뷰즈 원장(ip_hash = sha256(salt+ip)); 가입으로 이어지면 claimed_by에 이메일이 남고
    같은 세션은 다시 못 쓴다(GUEST-3)."""

    __tablename__ = "guest_sessions"
    id: Mapped[str] = mapped_column(String(48), primary_key=True)
    ip_hash: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    turns_used: Mapped[int] = mapped_column(Integer, default=0)
    claimed_by: Mapped[str | None] = mapped_column(String(256), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class TurnUsage(Base):
    """PLAN-1: 쿼터·과금의 단위인 '턴' 원장 — 답변 시작 시 1행. Message 카운트를 쓰지 않는
    이유: 대화 삭제가 메시지를 지워 쿼터가 '환불'되는 구멍이 생긴다. day/month는 KST 기준
    문자열(YYYY-MM-DD / YYYY-MM) — "내일 0시에 충전돼요"가 유저의 자정과 일치해야 한다."""

    __tablename__ = "turn_usage"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_email: Mapped[str] = mapped_column(String(256), index=True)
    conversation_id: Mapped[str | None] = mapped_column(String(48), nullable=True)
    day: Mapped[str] = mapped_column(String(10), index=True)    # KST YYYY-MM-DD
    month: Mapped[str] = mapped_column(String(7), index=True)   # KST YYYY-MM
    ts: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class Conversation(Base):
    __tablename__ = "conversations"
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("cnv"))
    user_email: Mapped[str] = mapped_column(ForeignKey("users.email"), index=True)
    title: Mapped[str] = mapped_column(String(200), default="New chat")
    agent_id: Mapped[str | None] = mapped_column(String(48), nullable=True)  # which agent drove this chat
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class Message(Base):
    __tablename__ = "messages"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    conversation_id: Mapped[str] = mapped_column(ForeignKey("conversations.id"), index=True)
    role: Mapped[str] = mapped_column(String(16))
    content: Mapped[str] = mapped_column(Text)
    citations: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    # the turn's rendered charts/tables (JSON list) — so reopened conversations keep their
    # inline {{figure:N}} artifacts (the answer body references them by 1-based position).
    artifacts: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    # the QT-2 number audit (JSON {checked, supported, unsupported, ledger}) — so reopened
    # conversations keep the 판정 strip + the in-prose numeral highlights (LG-4).
    audit: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    # V-7: 공유 훅(발견 한 줄) — 재열람한 대화에서도 공유 제목으로 쓰인다.
    hook: Mapped[str | None] = mapped_column(String(160), nullable=True)
    # 더 파고들기 chips (JSON list of strings) — persisted so reopened conversations keep the
    # follow-up row instead of losing it with the ephemeral SSE stream.
    suggestions: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


# --- BILL/REF: 토스 빌링 구독 + 레퍼럴 크레딧 -------------------------------
class BillingCustomer(Base):
    """BILL-1: 유저↔토스 매핑. customer_key는 UUID(이메일 노출 금지), 빌링키는 Fernet 암호화
    저장 — 서버 밖으로 절대 나가지 않는다. card_label은 던닝 안내·중복카드 레퍼럴 가드용."""

    __tablename__ = "billing_customers"
    user_email: Mapped[str] = mapped_column(ForeignKey("users.email"), primary_key=True)
    customer_key: Mapped[str] = mapped_column(String(64), unique=True)
    billing_key_enc: Mapped[str | None] = mapped_column(Text, nullable=True)
    card_label: Mapped[str | None] = mapped_column(String(64), nullable=True)
    status: Mapped[str] = mapped_column(String(12), default="active")   # active | removed
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class Subscription(Base):
    """BILL-1: 구독 상태기계 — active →(과금 실패) past_due →(재시도 성공) active |
    (소진) canceled → apply_plan(free). 해지는 cancel_at_period_end(기간 끝까지 Pro 유지)."""

    __tablename__ = "subscriptions"
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("sub"))
    user_email: Mapped[str] = mapped_column(ForeignKey("users.email"), index=True)
    plan: Mapped[str] = mapped_column(String(24), default="pro")
    status: Mapped[str] = mapped_column(String(12), default="active")   # active | past_due | canceled
    current_period_start: Mapped[datetime] = mapped_column(DateTime)
    current_period_end: Mapped[datetime] = mapped_column(DateTime, index=True)
    cancel_at_period_end: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class Invoice(Base):
    """BILL-1: 청구서. order_id UNIQUE가 이중과금의 1차 방어(같은 기간 재시도는 같은 order_id
    → 토스가 멱등 처리). total = amount − discount − credit_applied."""

    __tablename__ = "invoices"
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("inv"))
    user_email: Mapped[str] = mapped_column(ForeignKey("users.email"), index=True)
    subscription_id: Mapped[str] = mapped_column(String(48), index=True)
    order_id: Mapped[str] = mapped_column(String(64), unique=True)
    amount: Mapped[int] = mapped_column(Integer)                 # 정가(KRW)
    discount: Mapped[int] = mapped_column(Integer, default=0)    # REF-2: 피추천 첫 달 할인 등
    credit_applied: Mapped[int] = mapped_column(Integer, default=0)  # REF-3: 크레딧 차감
    total: Mapped[int] = mapped_column(Integer)
    status: Mapped[str] = mapped_column(String(12), default="pending")  # pending|paid|failed|refunded
    toss_payment_key: Mapped[str | None] = mapped_column(String(200), nullable=True)
    attempts: Mapped[int] = mapped_column(Integer, default=0)
    next_retry_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    period_start: Mapped[datetime] = mapped_column(DateTime)
    period_end: Mapped[datetime] = mapped_column(DateTime)
    paid_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class WebhookEvent(Base):
    """BILL-4: 웹훅 멱등 원장 — event_id UNIQUE로 중복 배달을 무해화. 바디는 신뢰하지 않고
    paymentKey로 토스에 재조회해 검증한다."""

    __tablename__ = "webhook_events"
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    provider: Mapped[str] = mapped_column(String(16), default="toss")
    event_id: Mapped[str] = mapped_column(String(120), unique=True)
    payload: Mapped[str] = mapped_column(Text)
    processed_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class CreditLedger(Base):
    """REF-2: 구독 크레딧 원장(KRW, signed) — 잔액 = SUM. (kind, related_invoice_id, user_email)
    UNIQUE가 킥백/차감의 멱등을 보장한다. 현금 아님 — 다음 인보이스에서 자동 차감."""

    __tablename__ = "credit_ledger"
    __table_args__ = (
        UniqueConstraint("kind", "related_invoice_id", "user_email", name="uq_credit_once"),
    )
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_email: Mapped[str] = mapped_column(String(256), index=True)
    amount_krw: Mapped[int] = mapped_column(Integer)   # +적립 / −사용(차감)·회수
    kind: Mapped[str] = mapped_column(String(32))      # referral_kickback|invoice_application|clawback|admin_adjust
    related_invoice_id: Mapped[str | None] = mapped_column(String(48), nullable=True)
    related_user: Mapped[str | None] = mapped_column(String(256), nullable=True)
    note: Mapped[str | None] = mapped_column(String(200), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


# --- F1: configurable agents ----------------------------------------------
class Agent(Base):
    """A configurable agent. ``user_email is None`` marks a provided template
    (a starting point any user can pick or clone). ``data_sources`` is a JSON
    list of connector ids (or full tool names) the agent may use."""

    __tablename__ = "agents"
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("agt"))
    user_email: Mapped[str | None] = mapped_column(index=True, nullable=True)  # null = provided template
    name: Mapped[str] = mapped_column(String(120))
    description: Mapped[str | None] = mapped_column(String(280), nullable=True)
    model: Mapped[str] = mapped_column(String(64), default="gemini")  # gemini-only (invariant #7)
    system_prompt: Mapped[str | None] = mapped_column(Text, nullable=True)
    data_sources: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON list of connector ids
    is_template: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class Watchlist(Base):
    """A user's named group of companies (the ``@handle`` that chat + the analyst
    builder tag). ``name`` is unique per user and doubles as the @-handle."""

    __tablename__ = "watchlists"
    __table_args__ = (UniqueConstraint("user_email", "name", name="uq_watchlist_user_name"),)
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("wl"))
    user_email: Mapped[str] = mapped_column(ForeignKey("users.email"), index=True)
    name: Mapped[str] = mapped_column(String(80))  # the @handle, e.g. "반도체바스켓"
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class WatchlistItem(Base):
    """One company in a watchlist. A company may belong to many watchlists, so the
    uniqueness is per (watchlist, market, ticker), not global."""

    __tablename__ = "watchlist_items"
    __table_args__ = (
        UniqueConstraint("watchlist_id", "market", "ticker", name="uq_item_watchlist_market_ticker"),
    )
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("wli"))
    watchlist_id: Mapped[str] = mapped_column(ForeignKey("watchlists.id"), index=True)
    market: Mapped[str] = mapped_column(String(8))  # US | KR
    ticker: Mapped[str] = mapped_column(String(32))
    name: Mapped[str | None] = mapped_column(String(160), nullable=True)
    added_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class Board(Base):
    """A named canvas the user pins assets onto (charts, sources, text). Users can keep
    several; pinning offers a board picker. Notion-like free layout per item."""

    __tablename__ = "boards"
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("brd"))
    user_email: Mapped[str] = mapped_column(ForeignKey("users.email"), index=True)
    name: Mapped[str] = mapped_column(String(120))
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class PinnedArtifact(Base):
    """An asset the user pinned to a Board — a live artifact (chart/table), a source/evidence
    card (``spec.kind == 'source'``), or a text block (``spec.kind == 'text'``). ``spec`` is the
    JSON; chart pins are re-fetchable via tool+args (refresh). ``x/y/w/h`` are the Notion-like
    canvas layout (null until placed)."""

    __tablename__ = "pinned_artifacts"
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("pin"))
    user_email: Mapped[str] = mapped_column(ForeignKey("users.email"), index=True)
    # which board this asset lives on (nullable for legacy rows → treated as the default board)
    board_id: Mapped[str | None] = mapped_column(ForeignKey("boards.id"), index=True, nullable=True)
    title: Mapped[str] = mapped_column(String(200))
    spec: Mapped[str] = mapped_column(Text)  # JSON asset spec
    # free-canvas layout (px); null = not yet placed (web auto-flows it)
    x: Mapped[int | None] = mapped_column(Integer, nullable=True)
    y: Mapped[int | None] = mapped_column(Integer, nullable=True)
    w: Mapped[int | None] = mapped_column(Integer, nullable=True)
    h: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class Integration(Base):
    __tablename__ = "integrations"
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("int"))
    user_email: Mapped[str] = mapped_column(index=True)
    kind: Mapped[str] = mapped_column(String(24))  # telegram | slack
    config: Mapped[str] = mapped_column(Text)  # JSON (tokens/channels)
    enabled: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


# --- F3: notification alerts (board / widget scoped push) ------------------
class NotificationAlert(Base):
    """A standing watcher the user enables from the DASHBOARD — either for a whole board
    (``scope='board'`` → the board's key widgets) or a single widget (``scope='widget'`` →
    bound to one ``pin_id``). It evaluates ``trigger_type`` over ``params`` on a ``schedule``,
    and when due renders a SOURCED message (source · as_of · deep link — never advice/forecast)
    pushed to ``channels``. ``source_spec`` remembers the widget's tool+args so threshold
    triggers re-fetch live data and the message links back to the dashboard/explore evidence."""

    __tablename__ = "notification_alerts"
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("alt"))
    user_email: Mapped[str] = mapped_column(ForeignKey("users.email"), index=True)
    name: Mapped[str] = mapped_column(String(120))
    scope: Mapped[str] = mapped_column(String(8), default="board")  # board | widget
    board_id: Mapped[str | None] = mapped_column(String(48), index=True, nullable=True)
    pin_id: Mapped[str | None] = mapped_column(String(48), index=True, nullable=True)  # widget scope
    # earnings | rate | macro_indicator | filing_news | price_threshold | digest
    trigger_type: Mapped[str] = mapped_column(String(24))
    params: Mapped[str | None] = mapped_column(Text, nullable=True)      # JSON {target, threshold, ...}
    schedule: Mapped[str | None] = mapped_column(Text, nullable=True)    # JSON {freq, time?, every_minutes?}
    channels: Mapped[str] = mapped_column(Text, default="[]")            # JSON list of channel kinds
    quiet_hours: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON {start,end}
    status: Mapped[str] = mapped_column(String(8), default="active")     # active | paused
    source_spec: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON {tool, args, source, deeplink}
    last_fired_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    next_fire_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class NotificationDelivery(Base):
    """One message an alert pushed to one channel. Carries the full trust envelope
    (title/body/as_of/source/deeplink). ``status`` = sent | simulated | failed — ``simulated``
    means the channel had no credentials, so we recorded the message we *would* have sent (keeps
    the alert→delivery flow verifiable end-to-end without external accounts)."""

    __tablename__ = "notification_deliveries"
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("dlv"))
    alert_id: Mapped[str] = mapped_column(ForeignKey("notification_alerts.id"), index=True)
    user_email: Mapped[str] = mapped_column(index=True)  # denormalized for ownership scoping
    channel: Mapped[str] = mapped_column(String(24))     # telegram | slack | kakao | email
    title: Mapped[str] = mapped_column(String(240))
    body: Mapped[str] = mapped_column(Text)
    as_of: Mapped[str | None] = mapped_column(String(32), nullable=True)
    source: Mapped[str | None] = mapped_column(String(120), nullable=True)
    deeplink: Mapped[str | None] = mapped_column(String(240), nullable=True)
    status: Mapped[str] = mapped_column(String(12), default="sent")  # sent | simulated | failed
    sent_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class ChannelConnection(Base):
    """A user's connection to one messenger (BYO bot-token / webhook). Credentials live in
    ``config`` server-side only — never sent to the browser; the API exposes only whether
    credentials exist + ``verified``. One row per (user, channel)."""

    __tablename__ = "channel_connections"
    __table_args__ = (UniqueConstraint("user_email", "channel", name="uq_channel_user_kind"),)
    id: Mapped[str] = mapped_column(String(48), primary_key=True, default=lambda: _uid("chn"))
    user_email: Mapped[str] = mapped_column(index=True)
    channel: Mapped[str] = mapped_column(String(24))  # telegram | slack | kakao | email
    config: Mapped[str] = mapped_column(Text, default="{}")  # JSON creds (server-side only)
    verified: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())


class DashboardTemplate(Base):
    """A provided dashboard template (seeded, global). ``widgets`` is a JSON list of
    {spec(tool+args+viz+source), x, y, w, h} that ``POST /board/from-template`` materializes
    as pins on the user's chosen board."""

    __tablename__ = "dashboard_templates"
    id: Mapped[str] = mapped_column(String(48), primary_key=True)  # stable seed id (e.g. "dt_semi")
    name: Mapped[str] = mapped_column(String(120))
    description: Mapped[str | None] = mapped_column(String(280), nullable=True)
    market: Mapped[str | None] = mapped_column(String(8), nullable=True)  # US | KR | None(both)
    widgets: Mapped[str] = mapped_column(Text, default="[]")  # JSON list of {spec,x,y,w,h}
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
